### PR TITLE
Import module

### PR DESCRIPTION
**Pull request by javajawa**
- Adds the module almost as seen in https://github.com/mewbotorg/mewbot/pull/85 (some linting fixes for bandit have been applied
- Updates the template in use here with some core fixes, like installing mewbot-dev-tools locally

### CODE REVIEW

**Comment by javajawa** [comment]
Draft Status:
- [x] PyPi issue -- this is caused by the test.pypi.org key only existing on the dev tools repo and not the organisation.
- [ ] Readme needs to be updated to include info on this module
- [x] This PR is draft as I have draft comments on https://github.com/mewbotorg/mewbot/pull/85 this may still apply

**Comment by ajCameron** [comment]
Relevant comments from https://github.com/mewbotorg/mewbot/pull/85

@javajawa said

I found some notes:

- [x] Add test for creating dirs
- [x] Add test for binary write
- [x] Add test for attempting to write to ../ or /abs style paths
- [x] Add test for non-existent output dir
- [x] Add test for non-initialised output dir
- [x] Add test for no permission to create

**Comment by javajawa** [comment]
The draft comments on https://github.com/mewbotorg/mewbot/pull/85 (that I never published) have been fixed in https://github.com/mewbotorg/mewbot-io-file-storage/pull/3/commits/aa3ff720eb35372bfac28b3b071bf33cd7b142a0 and https://github.com/mewbotorg/mewbot-io-file-storage/pull/3/commits/d471345ce18e3a0b3d3fc98b01517e03189d5b3c

I believe all the test cases above have been covered.

**Review by ajCameron — APPROVED** [review]
Looks good to me! Tests are passing and code coverage is decent.

**Pull request merged**
